name: CDGitops

on:
  push:
    branches:
    - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Docker Build and Push
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/gitops
          tags: ${{ github.sha }}, latest

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: 'v4.4.0'

      - name: Update Kubernetes resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd k8s
          kustomize edit set image goserver=$DOCKER_USERNAME/gitops:$GITHUB_SHA

      - name: Commit
        run: |
          git config --local user.name "action.github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump docker version [skip ci]"
          
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: Leonardomdeoli/gitops